// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutImagePreview: typeof import('@nutui/nutui-taro')['ImagePreview']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSticky: typeof import('@nutui/nutui-taro')['Sticky']
  }
}
